steps:
# - name: 'ubuntu'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     ls -alR > file
# - name: 'ubuntu'
#   args: ['cat', 'file']
- name: gcr.io/kaniko-project/executor
  args: [
    '--destination=gcr.io/$PROJECT_ID/pspadmin:$SHORT_SHA',
    '--cache-repo=gcr.io/$PROJECT_ID/pspadmin',
    '--cache=true',
    '--cache-ttl=6h',
  ]
- name: gcr.io/$PROJECT_ID/pspadmin:$SHORT_SHA
  entrypoint: 'node'
  args: ['--version']
images: ['gcr.io/$PROJECT_ID/pspadmin:$SHORT_SHA']